export enum PlayerPositionEnum {
    ST = 'ST',
    CF = 'CF',
    LF = 'LF',
    RF = 'RF',
    AM = 'AM',
    LM = 'LM',
    RM = 'RM',
    CM = 'CM',
    DM = 'DM',
    CB = 'CB',
    LB = 'LB',
    RB = 'RB',
    GK = 'GK',
}